prompt: grass, tactile paving, line-type tactile paving
threshold: 0.49999999999999994
score_min: 0.3
classes:
  grass:
    id: 3
    color:
    - 0
    - 255
    - 0
  tactile paving:
    id: 4
    color:
    - 255
    - 255
    - 0
  line-type tactile paving:
    id: 4
    color:
    - 255
    - 255
    - 0
class_thresholds:
  grass: 0.3
  tactile paving: 0.3
  line-type tactile paving: 0.3
